# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import psycopg2
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 350)
        MainWindow.setStyleSheet("background-color: rgb(27, 27, 39);\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-4, -1, 311, 321))
        self.tabWidget.setObjectName("tabWidget")
        self.signup_tab = QtWidgets.QWidget()
        self.signup_tab.setObjectName("signup_tab")
        self.signup_name_line = QtWidgets.QLineEdit(self.signup_tab)
        self.signup_name_line.setPlaceholderText("Name")
        self.signup_name_line.setGeometry(QtCore.QRect(50, 110, 211, 27))
        self.signup_name_line.setObjectName("signup_name_line")
        self.signup_btn = QtWidgets.QPushButton(self.signup_tab)
        self.signup_btn.setGeometry(QtCore.QRect(110, 210, 87, 27))
        self.signup_btn.setObjectName("signup_btn")
        self.signup_email_line = QtWidgets.QLineEdit(self.signup_tab)
        self.signup_email_line.setPlaceholderText("Email")
        self.signup_email_line.setGeometry(QtCore.QRect(50, 60, 211, 27))
        self.signup_email_line.setObjectName("signup_email_line")
        self.signup_password_line = QtWidgets.QLineEdit(self.signup_tab)
        self.signup_password_line.setPlaceholderText("Password")
        self.signup_password_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.signup_password_line.setGeometry(QtCore.QRect(50, 160, 211, 27))
        self.signup_password_line.setObjectName("signup_password_line")
        self.tabWidget.addTab(self.signup_tab, "")
        self.login_tab = QtWidgets.QWidget()
        self.login_tab.setObjectName("login_tab")
        self.login_password_line = QtWidgets.QLineEdit(self.login_tab)
        self.login_password_line.setPlaceholderText("Password")
        self.login_password_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.login_password_line.setGeometry(QtCore.QRect(50, 120, 211, 27))
        self.login_password_line.setObjectName("login_password_line")
        self.login_btn = QtWidgets.QPushButton(self.login_tab)
        self.login_btn.setGeometry(QtCore.QRect(110, 170, 87, 27))
        self.login_btn.setObjectName("login_btn")
        self.login_name_line = QtWidgets.QLineEdit(self.login_tab)
        self.login_name_line.setPlaceholderText("Name")
        self.login_name_line.setGeometry(QtCore.QRect(50, 70, 211, 27))
        self.login_name_line.setObjectName("login_name_line")
        self.tabWidget.addTab(self.login_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # self.insert_to_db()
        self.signup_btn.clicked.connect(self.insert_to_db)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Authorization"))
        self.signup_btn.setText(_translate("MainWindow", "Sign Up"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.signup_tab), _translate("MainWindow", "Sign Up"))
        self.login_btn.setText(_translate("MainWindow", "Log In"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.login_tab), _translate("MainWindow", "Log In"))

    def insert_to_db(self):
        conn = psycopg2.connect(database='test', user='postgres', host='localhost', port='5432', password='<password>')

        cur = conn.cursor()
        # -----------------
        cur.execute("""CREATE TABLE parameters (
            id serial PRIMARY KEY,
            name text,
            email text,
            password text
        );
        """)

        query = """INSERT INTO parameters (name, email, password) VALUES (%s, %s, %s)"""
        insert = (self.signup_name_line.text(),
                  self.signup_email_line.text(),
                  self.signup_password_line.text())

        cur.execute(query, insert)
        # -----------------
        conn.commit()
        cur.close()
        conn.close()
        self.signup_name_line.setText('')
        self.signup_email_line.setText('')
        self.signup_password_line.setText('')

        MainWindow.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
